name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: whtjddlr
          template: classic
          config_display: compact
          base: header, repositories, metadata
          config_timezone: Asia/Seoul
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_topics: yes
          plugin_topics_limit: 10
          plugin_lines: yes
