name: Update recent activity

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.0
        with:
          GH_USERNAME: whtjddlr
          MAX_LINES: 4
          COMMIT_MSG: "Update recent activity"
