name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: whtjddlr
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=3B82F6&color_dots=%23ECFDF5,%23D1FAE5,%2386EFAC,%234ADE80,%2316A34A

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
